### ISSUE TITLE
Add support for map prefix

### ISSUE THREAD

**Issue by kus** [ManifestManah/MapConfigurator#2]
Can you add support for map prefix's so we can make a script that gets executed for all surf maps `surf_.cfg` instead of having to make a config for every surf map?

It would execute in the following order:

1. `surf_.cfg`
2. `surf_kitsune_.cfg`
3. `surf_kitsune_v2.cfg`

The same way [this plugin](https://forums.alliedmods.net/showthread.php?p=607079) worked for SourceMod.

**Comment by ManifestManah** [comment]
This suggestion has been implemented. The MapConfigurator now supports map name prefixes, and the plugin comes with a list of already predefined map prefix configuration files as an example on how they should be used.
